import Link from "next/link";
import Head from "next/head";

import styles from "../styles/Layout.module.scss";

export default function Layout({ children }) {
  return (
    <div className={styles.layout}>
      <Head>
        <title>laragabathuler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav>
          <Link href="/">test</Link>
          <Link href="/about">About</Link>
        </nav>
      </header>
      <div className={styles.children}>{children}</div>
      <footer className={styles.footer}>
        <a className={styles.mail} href="mailto:larataba@gmail.com">
          Mail︎︎︎
        </a>
        <p className={styles.copyright}>
          ©2021 Lara Gabathuler. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
