backend:
  name: github
  repo: conblem/laragabathuler
  branch: main
  base_url: https://www.laragabathuler.ch/
  auth_endpoint: api/auth
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - label: "Seiten"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.mdx"
        fields:
          - label: "Titel"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"

  - label: "Projekte"
    name: "projects"
    folder: "content/projects/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{id}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "ID"
        name: "id"
        widget: "string"
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Cover"
        name: "cover"
        widget: "image"
      - label: "Startseiten Hover"
        name: "hover"
        widget: "string"
      - label: "Zusammenfassung"
        name: "summary"
        widget: "markdown"
      - label: "Beschreibung"
        name: "description"
        widget: "markdown"
      - label: "Content"
        name: "body"
        widget: "markdown"
