import Head from "next/head";
import Link from "next/link";
import Thumbnail from "../components/Thumbnail";
import styles from "../styles/Home.module.scss";

import { getAllProjectIds } from "../lib/projects";

export async function getStaticProps() {
  let projects = getAllProjectIds();
  return {
    props: {
      projects,
    },
  };
}

export default function Home({ projects }) {
  const thumbnails = projects.map((project) => (
    <Link key={project} href={`/projects/${project}`}>
      <Thumbnail
        hover={project}
        src="https://raw.githubusercontent.com/conblem/lara/master/src/assets/image1.jpeg?token=AEXPEIITSDQ4IH7DAHQ5ZZDAYHGV2"
      ></Thumbnail>
    </Link>
  ));

  return (
    <div className={`${styles.home} columns is-desktop is-multiline`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {thumbnails}
    </div>
  );
}
