import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import Content from "../components/Content";
import { getProjects } from "../lib/projects";
import styles from "../styles/Home.module.scss";

export async function getStaticProps() {
  let projects = await getProjects();
  return {
    props: {
      projects: projects.map(({ data }) => data),
    },
  };
}

function Project({ id, cover, hover, title }) {
  return (
    <Link key={id} href={`/projects/${id}`}>
      <a className="column is-half-desktop">
        <Content hover={hover} aspectX={2500} aspectY={1441}>
          <Image alt={title} src={cover} layout="fill" objectFit="cover" />
        </Content>
      </a>
    </Link>
  );
}

export default function Home({ projects }) {
  const thumbnails = projects.map((props) => (
    <Project {...props} key={props.id} />
  ));

  return (
    <div className={`${styles.home} columns is-desktop is-multiline`}>
      <Head>
        <title>laragabathuler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {thumbnails}
    </div>
  );
}
